### ISSUE TITLE
这个能否支持用struct做载体呢？

### ISSUE THREAD

**Issue by ccllong** [smartwalle/dba#1]
在update和add的时候，能否支持setMap相同的setStruct？

**Comment by smartwalle** [comment]
技术上是可行的，但目前并没有实现这个功能。

**Comment by ccllong** [comment]
那有没一种封装方式，可以做到跟java spring里面更新东西时，对于没有传值或是不需要更新的字段不做更新，只构造出所需要更新字段的sql

**Comment by smartwalle** [comment]
其实当前我在考虑 SetMap  这个方法的时候，就是出于你说的这个目的，将 http 的请求参数转换为一个 map， 当然我是配合 https://github.com/smartwalle/form 来使用的，有兴趣，可以看看 form 的 CleanedData， readme 里面有。

**Comment by ccllong** [comment]
感觉你这个form还不是最通用的，更多是更新数据时，想根据客户端提交 的几个有变化 的字段来生成出一个对应的sql，这个方式我觉得比较兼容于大多数使用go的人，这样对原有的代码侵入性最低

**Comment by smartwalle** [comment]
你的意思是，客户端提交了n个字段，但是需要判断出那几个字段有变化？

**Comment by ccllong** [comment]
是的，就是客户端提交了只变更的字段，而我们映射进struct，此时我们在生成sql的时候需要只生成那些有提交的字段更新语句，而没有提交 的那些字段的更新语句不生成，以免覆盖，当然因为struct的默认值问题，所以我在想这个是不是会受限语言本身特性而无法处理

**Comment by smartwalle** [comment]
这个事情我个人觉得不应该放在数据库层面去处理，在入库之前要判断相关字段的值是否有变更，那至少得把变更之前（返回给客户端的数据）的数据缓存起来，待收到客户端的请求之后，对字段的值进行对比。

**Comment by smartwalle** [comment]
当然还有一种办法就是客户端判断那些字段有变更，只传有变更的字段给服务器端。

**Comment by ccllong** [comment]
一定不在数据层处理，在service层用封装的组件处理完再进数据层，我想要的就是只传变更的字段给服务端，但传过来我们需要做一个判断比对，有些字段可能根本不存在于我们的struct里，这才是我今天在找的解决方案的问题

**Comment by smartwalle** [comment]
那我上面发的 form 就有你需要的这个功能呀，form 里面定义好需要的字段，最终 CleanedData 里面只会包含 form 里面定义的字段（form 里面定义了的字段，如果客户端没有提交，也不会进入CleanedData），客户端提交的多余的参数会被过滤掉。

如果 form 里面的 tag 名称和数据库的字段名称一致，那么就可以直接把 CleanedData 传递给 SetMap 方法了。

**Comment by ccllong** [comment]
你的这个需要配默认值不是么？

**Comment by ccllong** [comment]
再着你要标tag，实际上我们在用的时候都已经把tag用于json和db上标了，除非新开结构体，但这样只会让结构体好多重名的维护麻烦

**Comment by smartwalle** [comment]
默认值是可选的，对于一些字段，难免会出现要求提供默认值的情况；关于tag，不一定非要用form，在 form 项目里面的  binding.go 文件中，可以把tag改成任意你想要的名字。
