### ISSUE TITLE
Builder 结构体复用

### ISSUE THREAD

**Issue by xyanyue** [smartwalle/dba#2]
>>> 比如 InsertBuilder复用，只需要Exec完之后，清空结构体中values就行了。在insert.go 180行加入：
```Golang
this.values = this.values[:0]
```

**Comment by smartwalle** [comment]
在 Exec 完之后自动把 values 清空掉，可能不太友好，我添加了一个 Clone 方法，在 test 文件中有示例，可以看一下能否满足你的需求。
