### ISSUE TITLE
what happened?

### ISSUE THREAD

**Issue by wilson2016** [smartwalle/dba#4]
InsertBuilder Exec Failed: Error 1213: Deadlock found when trying to get lock; try restarting transaction
这个是因为并发量太大吗？

**Comment by smartwalle** [comment]
这个因为是你开启了太多的事务，然后事务没有提交或者回滚引起的。

**Comment by smartwalle** [comment]
这个应该是你开启了太多的事务，然后事务没有提交或者回滚引起的。

**Comment by wilson2016** [comment]
能给个例子吗？提交和回滚的

**Comment by smartwalle** [comment]
你发的这个错误是数据库报的，原因就是开启了太多的事物，这个和InsertBuilder无关。

**Comment by wilson2016** [comment]
同时批量写3000条数据可以吗？我在日志在同时写3000，4000大量报错

**Comment by smartwalle** [comment]
读写的能力是由你的数据库决定的，这个工具只是负责生成 SQL 语句，不过批量写入3k条数据，这个量可能有点大。
